# phpcms bakfile
# version:PHPCMS V9
# time:2013-07-02 09:33:17
# type:phpcms
# phpcms:http://www.phpcms.cn
# --------------------------------------------------------


DROP TABLE IF EXISTS `v9_model`;
CREATE TABLE `v9_model` (
  `modelid` smallint(5) unsigned NOT NULL auto_increment,
  `siteid` smallint(5) unsigned NOT NULL default '0',
  `name` char(30) NOT NULL,
  `description` char(100) NOT NULL,
  `tablename` char(20) NOT NULL,
  `setting` text NOT NULL,
  `addtime` int(10) unsigned NOT NULL default '0',
  `items` smallint(5) unsigned NOT NULL default '0',
  `enablesearch` tinyint(1) unsigned NOT NULL default '1',
  `disabled` tinyint(1) unsigned NOT NULL default '0',
  `default_style` char(30) NOT NULL,
  `category_template` char(30) NOT NULL,
  `list_template` char(30) NOT NULL,
  `show_template` char(30) NOT NULL,
  `js_template` varchar(30) NOT NULL,
  `sort` tinyint(3) NOT NULL,
  `type` tinyint(1) NOT NULL,
  PRIMARY KEY  (`modelid`),
  KEY `type` (`type`,`siteid`)
) ENGINE=MyISAM AUTO_INCREMENT=34 DEFAULT CHARSET=utf8;

INSERT INTO `v9_model` VALUES('17','1','TAG模型','TAG模型','tags','','0','0','1','0','default','category','list','show','','0','0');
INSERT INTO `v9_model` VALUES('10','1','普通会员','普通会员','member_detail','','0','0','1','0','','','','','','0','2');
INSERT INTO `v9_model` VALUES('12','1','电视EPG模型','电视EPG模型','channelepg','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('13','1','视频模型','视频模型','video','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('16','1','直播频道分类','直播频道分类','channel_category','','0','0','1','0','default','category','list','show','','0','0');
INSERT INTO `v9_model` VALUES('14','1','终端分类','终端分类','term_type','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('15','1','栏目分类','栏目分类','column','','0','0','1','0','default','category','list','show','','0','0');
INSERT INTO `v9_model` VALUES('20','1','地域分类','地域分类','column_content_area','','0','0','1','0','default','category','list','show','','0','0');
INSERT INTO `v9_model` VALUES('19','1','推荐位分类','推荐位分类','postion_type','','0','0','1','0','default','category','list','show','','0','0');
INSERT INTO `v9_model` VALUES('21','1','栏目按内容类型分类','栏目按内容类型分类','column_content_cate','','0','0','1','0','default','category','list','show','','0','0');
INSERT INTO `v9_model` VALUES('22','1','栏目终端类型映射','栏目终端类型映射','column_mapping','','0','0','1','0','default','category','list','show','','0','0');
INSERT INTO `v9_model` VALUES('23','1','直播频道模型','直播频道模型','channel','','0','0','1','0','default','category','list','show','','0','0');
INSERT INTO `v9_model` VALUES('24','1','视频内容模型','视频内容模型','video_content','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('25','1','视频海报模型','视频海报模型','video_poster','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('26','1','客户端版本','客户端版本','client_version','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('27','1','图片服务器','图片服务器','pic_server','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('28','1','广告位模型','广告位模型','adverts','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('31','1','游戏类型','游戏类型','game_type','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('32','1','游戏模型','游戏模型','game','','0','0','1','0','','','','','','0','0');
INSERT INTO `v9_model` VALUES('33','1','视频来源','视频来源','video_source','','0','0','1','0','','','','','','0','0');

DROP TABLE IF EXISTS `v9_model_field`;
CREATE TABLE `v9_model_field` (
  `fieldid` mediumint(8) unsigned NOT NULL auto_increment,
  `modelid` smallint(5) unsigned NOT NULL default '0',
  `siteid` smallint(5) unsigned NOT NULL default '0',
  `field` varchar(20) NOT NULL,
  `name` varchar(30) NOT NULL,
  `tips` text NOT NULL,
  `css` varchar(30) NOT NULL,
  `minlength` int(10) unsigned NOT NULL default '0',
  `maxlength` int(10) unsigned NOT NULL default '0',
  `pattern` varchar(255) NOT NULL,
  `errortips` varchar(255) NOT NULL,
  `formtype` varchar(20) NOT NULL,
  `setting` mediumtext NOT NULL,
  `formattribute` varchar(255) NOT NULL,
  `unsetgroupids` varchar(255) NOT NULL,
  `unsetroleids` varchar(255) NOT NULL,
  `iscore` tinyint(1) unsigned NOT NULL default '0',
  `issystem` tinyint(1) unsigned NOT NULL default '0',
  `isunique` tinyint(1) unsigned NOT NULL default '0',
  `isbase` tinyint(1) unsigned NOT NULL default '0',
  `issearch` tinyint(1) unsigned NOT NULL default '0',
  `isadd` tinyint(1) unsigned NOT NULL default '0',
  `isfulltext` tinyint(1) unsigned NOT NULL default '0',
  `isposition` tinyint(1) unsigned NOT NULL default '0',
  `listorder` mediumint(8) unsigned NOT NULL default '0',
  `disabled` tinyint(1) unsigned NOT NULL default '0',
  `isomnipotent` tinyint(1) unsigned NOT NULL default '0',
  PRIMARY KEY  (`fieldid`),
  KEY `modelid` (`modelid`,`disabled`),
  KEY `field` (`field`,`modelid`)
) ENGINE=MyISAM AUTO_INCREMENT=707 DEFAULT CHARSET=utf8;

INSERT INTO `v9_model_field` VALUES('289','19','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('243','17','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('244','17','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('245','17','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('275','19','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('247','17','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('251','17','1','type','标签类型','1=地域，2=内容分类','','0','0','','','box','array (\n  \'options\' => \'请选择|\r\n地域|1\r\n内容分类|2\',\n  \'boxtype\' => \'select\',\n  \'fieldtype\' => \'tinyint\',\n  \'minnumber\' => \'-1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','0','3','0','0');
INSERT INTO `v9_model_field` VALUES('249','17','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('301','20','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('298','20','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','2','0','0');
INSERT INTO `v9_model_field` VALUES('299','20','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('294','19','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('317','20','1','col_id','栏目分类','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_column\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'title\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','1','1','1','0','1','0','0');
INSERT INTO `v9_model_field` VALUES('290','19','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('292','19','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('227','16','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('232','17','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('233','17','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('235','17','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('296','20','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('297','20','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','3','1','0');
INSERT INTO `v9_model_field` VALUES('303','20','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('276','19','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','2','1','0');
INSERT INTO `v9_model_field` VALUES('277','19','1','title','推荐位类型','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('278','19','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('280','19','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('313','20','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('315','20','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('282','19','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('309','20','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('310','20','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('311','20','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('225','16','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('226','16','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  \'minnumber\' => \'1\',\n  \'maxnumber\' => \'99999\',\n  \'decimaldigits\' => \'0\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','1','0');
INSERT INTO `v9_model_field` VALUES('230','17','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('231','17','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','2','1','0');
INSERT INTO `v9_model_field` VALUES('223','16','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('221','16','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('222','16','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('307','20','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('218','16','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('219','16','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('237','17','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('306','20','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('285','19','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('215','16','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('286','19','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('288','19','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('240','17','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('241','17','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('213','16','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('210','16','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('211','16','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('209','16','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','3','1','0');
INSERT INTO `v9_model_field` VALUES('83','10','1','birthday','生日','','','0','0','','生日格式错误','datetime','array (\n  \'fieldtype\' => \'date\',\n  \'format\' => \'Y-m-d\',\n  \'defaulttype\' => \'0\',\n)','','','','0','0','0','0','0','1','1','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('466','13','1','pub_date','上线日期','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'date\',\n  \'format\' => \'Y-m-d Ah:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','1','1','1','0','1','9','0','0');
INSERT INTO `v9_model_field` VALUES('120','12','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('118','12','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('119','12','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('464','12','1','epgid','epgid','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('116','12','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('115','12','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','20','0','0');
INSERT INTO `v9_model_field` VALUES('467','13','1','offline_date','下线日期','上线日期+3个月','','0','0','','','datetime','array (\n  \'fieldtype\' => \'date\',\n  \'format\' => \'Y-m-d Ah:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','1','1','1','0','1','11','0','0');
INSERT INTO `v9_model_field` VALUES('112','12','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','30','1','0');
INSERT INTO `v9_model_field` VALUES('110','12','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','21','0','0');
INSERT INTO `v9_model_field` VALUES('108','12','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','20','1','0');
INSERT INTO `v9_model_field` VALUES('368','12','1','systemdate','systemdate','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'date\',\n  \'format\' => \'Y-m-d Ah:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','1','2','0','0');
INSERT INTO `v9_model_field` VALUES('107','12','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','0','0','0');
INSERT INTO `v9_model_field` VALUES('106','12','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','20','1','0');
INSERT INTO `v9_model_field` VALUES('105','12','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('122','12','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('124','12','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('126','13','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('127','13','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','112','1','0');
INSERT INTO `v9_model_field` VALUES('128','13','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('129','13','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','110','1','0');
INSERT INTO `v9_model_field` VALUES('403','24','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('131','13','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','112','0','0');
INSERT INTO `v9_model_field` VALUES('402','13','1','ispackage','是否为总集','仅用于电视剧，电视栏目','','0','0','','','box','array (\n  \'options\' => \'是|1\r\n否|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'0\',\n  \'outputtype\' => \'0\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','1','19','0','0');
INSERT INTO `v9_model_field` VALUES('404','24','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','100','1','0');
INSERT INTO `v9_model_field` VALUES('405','24','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','1','0');
INSERT INTO `v9_model_field` VALUES('406','24','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','100','1','0');
INSERT INTO `v9_model_field` VALUES('133','13','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','114','1','0');
INSERT INTO `v9_model_field` VALUES('454','23','1','uuidSTB_HIGH','uuidSTB_HIGH','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','13','0','0');
INSERT INTO `v9_model_field` VALUES('410','24','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','100','1','0');
INSERT INTO `v9_model_field` VALUES('401','13','1','rating','评分','评分为：<span style=\"color:red; font-weight:bold;\">0 ~ 10 整数</style>','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','13','0','0');
INSERT INTO `v9_model_field` VALUES('136','13','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','117','0','0');
INSERT INTO `v9_model_field` VALUES('137','13','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','118','1','0');
INSERT INTO `v9_model_field` VALUES('139','13','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','150','0','0');
INSERT INTO `v9_model_field` VALUES('140','13','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','151','0','0');
INSERT INTO `v9_model_field` VALUES('141','13','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','153','0','0');
INSERT INTO `v9_model_field` VALUES('408','24','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('143','13','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','155','0','0');
INSERT INTO `v9_model_field` VALUES('145','13','1','username','添加人','','','0','20','','','text','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','1','1','0','1','0','0','0','0','198','0','0');
INSERT INTO `v9_model_field` VALUES('147','12','1','starttime','开始时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'datetime\',\n  \'format\' => \'Y-m-d Ah:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','1','1','1','0','0','5','0','0');
INSERT INTO `v9_model_field` VALUES('148','12','1','endtime','结束时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'datetime\',\n  \'format\' => \'Y-m-d Ah:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','1','1','1','0','0','6','0','0');
INSERT INTO `v9_model_field` VALUES('149','13','1','column_id','视频分类','','','0','0','/^[0-9.-]+$/','','box','array (\n  \'options\' => \'电视栏目|3\r\n电视剧|4\r\n电影|5\r\n乐酷|6\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','0','1','0','0','7','0','0');
INSERT INTO `v9_model_field` VALUES('468','13','1','long_desc','详细介绍','','','0','0','','','textarea','array (\n  \'width\' => \'100%\',\n  \'height\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'enablehtml\' => \'0\',\n)','','','','0','0','0','1','0','1','0','1','6','0','0');
INSERT INTO `v9_model_field` VALUES('152','13','1','active','是否可用','','','0','0','','','box','array (\n  \'options\' => \'可用|1\r\n不可用|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'smallint\',\n  \'minnumber\' => \'-1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'\',\n  \'outputtype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','0','15','0','0');
INSERT INTO `v9_model_field` VALUES('153','13','1','director','导演或主持人','多个用逗号隔开','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','0','2','0','0');
INSERT INTO `v9_model_field` VALUES('688','33','1','type','类型','','','0','0','','','box','array (\n  \'options\' => \'原始链接|raw\r\n防盗链链|redirect\r\n站外链接|web \',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'\',\n  \'outputtype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','0','1','0','0');
INSERT INTO `v9_model_field` VALUES('155','13','1','is_free','是否免费','','','0','0','','','box','array (\n  \'options\' => \'收费|0\r\n免费|1\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'tinyint\',\n  \'minnumber\' => \'-1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'0\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','0','1','0','0','14','0','0');
INSERT INTO `v9_model_field` VALUES('156','13','1','run_time','视频时长','时长单位为：<span style=\"color:red; font-weight:bold;\">秒（整数）</style>','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','0','10','0','0');
INSERT INTO `v9_model_field` VALUES('157','13','1','year_released','发行日期','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','0','0','8','0','0');
INSERT INTO `v9_model_field` VALUES('159','13','1','total_episodes','总集数','仅用于电视剧，电视栏目，且此视频为总集时有意义；','','0','0','','','number','array (\n  \'minnumber\' => \'1\',\n  \'maxnumber\' => \'\',\n  \'decimaldigits\' => \'0\',\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'rangetype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','0','20','0','0');
INSERT INTO `v9_model_field` VALUES('161','13','1','episode_number','分集为第几集（期）','仅用于电视剧、电视栏目，且此视频为分集时有意义；电视剧值为数字，表示第几集；电视栏目值为日期（如20121101），表示第几期','','0','0','','','number','array (\n  \'minnumber\' => \'1\',\n  \'maxnumber\' => \'\',\n  \'decimaldigits\' => \'0\',\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'rangetype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','0','23','0','0');
INSERT INTO `v9_model_field` VALUES('162','13','1','latest_episode_num','最新更新到第几集（期）','仅用于电视剧，电视栏目，且此视频为总集时有意义；电视剧值为数字，表示第几集；电视栏目值为日期（如20121101），表示第几期','','0','0','','','number','array (\n  \'minnumber\' => \'1\',\n  \'maxnumber\' => \'\',\n  \'decimaldigits\' => \'0\',\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'rangetype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','0','21','0','0');
INSERT INTO `v9_model_field` VALUES('163','13','1','actor','演员','多个演员用逗号隔开','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','0','3','0','0');
INSERT INTO `v9_model_field` VALUES('164','13','1','tag','TAG标签',' <input type=\"button\" value=\"从列表选择\" id=\"tag_pop_menu\" class=\"button\" />  多个标签用逗号(,)隔开','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','0','7','0','0');
INSERT INTO `v9_model_field` VALUES('165','14','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');
INSERT INTO `v9_model_field` VALUES('166','14','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','2','1','0');
INSERT INTO `v9_model_field` VALUES('167','14','1','title','终端类型','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','4','0','0');
INSERT INTO `v9_model_field` VALUES('168','14','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('187','15','1','catid','栏目管理','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','','','','','0','1','0','1','1','1','0','0','1','0','0');
INSERT INTO `v9_model_field` VALUES('170','14','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('194','15','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('172','14','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('192','15','1','updatetime','更新时间','','','0','0','','','datetime','array (\n  \'dateformat\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'1\',\n  \'defaultvalue\' => \'\',\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('175','14','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('176','14','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('178','14','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('179','14','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('180','14','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('190','15','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('182','14','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('188','15','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','0','1','0');
INSERT INTO `v9_model_field` VALUES('189','15','1','title','栏目名称','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','4','0','0');
INSERT INTO `v9_model_field` VALUES('184','14','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('197','15','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('198','15','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('200','15','1','url','URL','','','0','100','','','text','array (\n)','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('201','15','1','listorder','排序','','','0','6','','','number','array (\n)','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('202','15','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('204','15','1','status','状态','','','0','2','','','box','array (\n)','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('206','15','1','username','用户名','','','0','20','','','text','array (\n)','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('208','16','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('318','21','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('319','21','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','2','1','0');
INSERT INTO `v9_model_field` VALUES('320','21','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('321','21','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('347','22','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('323','21','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('369','12','1','text','text','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','0','4','0','0');
INSERT INTO `v9_model_field` VALUES('396','23','1','channel_id','节目ID','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','0','3','0','0');
INSERT INTO `v9_model_field` VALUES('372','23','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('373','23','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','100','1','0');
INSERT INTO `v9_model_field` VALUES('325','21','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('342','22','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('343','22','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('395','12','1','channel_id','频道ID','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_channel\',\n  \'select_title\' => \'channel_id,title\',\n  \'like_title\' => \'title\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'channel_id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','0','1','1','0','3','0','0');
INSERT INTO `v9_model_field` VALUES('345','22','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('328','21','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('329','21','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('341','22','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','2','1','0');
INSERT INTO `v9_model_field` VALUES('331','21','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('332','21','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('333','21','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('340','22','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('335','21','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('339','21','1','col_id','栏目分类','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_column\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'title\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','1','1','1','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('337','21','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('363','13','1','short_desc','视频简介','','','0','0','','','textarea','array (\n  \'width\' => \'100%\',\n  \'height\' => \'46\',\n  \'defaultvalue\' => \'\',\n  \'enablehtml\' => \'0\',\n)','','','','0','0','0','1','0','1','1','1','5','0','0');
INSERT INTO `v9_model_field` VALUES('364','12','1','uuidPC_HIGH','uuidPC_HIGH','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','1','11','0','0');
INSERT INTO `v9_model_field` VALUES('365','12','1','uuidIOS_HIGH','uuidIOS_HIGH','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','1','12','0','0');
INSERT INTO `v9_model_field` VALUES('366','12','1','uuidSTB_HIGH','uuidSTB_HIGH','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','1','13','0','0');
INSERT INTO `v9_model_field` VALUES('350','22','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('351','22','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('353','22','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('354','22','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('355','22','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('362','22','1','term_id','终端类型','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_term_type\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'title\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','1','1','1','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('357','22','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('361','22','1','col_id','栏目分类','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_column\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'title\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','1','1','1','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('359','22','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('374','23','1','title','电视台名称','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('375','23','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('377','23','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('448','24','1','clarity','清晰度','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','4','0','0');
INSERT INTO `v9_model_field` VALUES('413','24','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('414','24','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','100','1','0');
INSERT INTO `v9_model_field` VALUES('416','24','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('417','24','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('418','24','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('379','23','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','100','1','0');
INSERT INTO `v9_model_field` VALUES('451','23','1','iswidth','尺寸','','','1','0','','','box','array (\n  \'options\' => \'4:3|4:3\r\n16:9|16:9\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'width\' => \'\',\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'4:3\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','1','1','1','1','4','0','0');
INSERT INTO `v9_model_field` VALUES('452','23','1','uuidPC_HIGH','uuidPC_HIGH','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','11','0','0');
INSERT INTO `v9_model_field` VALUES('453','23','1','uuidIOS_HIGH','uuidIOS_HIGH','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','12','0','0');
INSERT INTO `v9_model_field` VALUES('382','23','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('383','23','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','100','1','0');
INSERT INTO `v9_model_field` VALUES('385','23','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('386','23','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('387','23','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('389','23','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('391','23','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('420','24','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('445','23','1','channel_category','节目类型','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_channel_category\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'title\',\n  \'where_title\' => \'\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','1','1','1','1','2','0','0');
INSERT INTO `v9_model_field` VALUES('422','24','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('447','24','1','path','播放链接','<input type=\"button\" value=\" PPTV链接搜索 \" id=\"path_pop_menu\" class=\"button\" />','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','3','0','0');
INSERT INTO `v9_model_field` VALUES('424','25','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('425','25','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','100','1','0');
INSERT INTO `v9_model_field` VALUES('426','25','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','1','0');
INSERT INTO `v9_model_field` VALUES('427','25','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','100','1','0');
INSERT INTO `v9_model_field` VALUES('429','25','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('431','25','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','100','1','0');
INSERT INTO `v9_model_field` VALUES('434','25','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('435','25','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','100','1','0');
INSERT INTO `v9_model_field` VALUES('437','25','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('438','25','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('439','25','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('441','25','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('443','25','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('457','23','1','uuidPC_MEDIUM','uuidPC_MEDIUM','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','14','0','0');
INSERT INTO `v9_model_field` VALUES('458','23','1','uuidIOS_MEDUIM','uuidIOS_MEDUIM','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','15','0','0');
INSERT INTO `v9_model_field` VALUES('459','23','1','uuidSTB_MEDIUM','uuidSTB_MEDIUM','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','16','0','0');
INSERT INTO `v9_model_field` VALUES('473','23','1','img','台标','列表界面使用','','0','0','','','image','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'0\',\n  \'upload_maxsize\' => \'\',\n  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','1','0','1','0','1','0','0','0');
INSERT INTO `v9_model_field` VALUES('461','12','1','uuidIOS_MEDUIM','uuidIOS_MEDUIM','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','14','0','0');
INSERT INTO `v9_model_field` VALUES('462','12','1','uuidPC_MEDIUM','uuidPC_MEDIUM','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','15','0','0');
INSERT INTO `v9_model_field` VALUES('463','12','1','uuidSTB_MEDIUM','uuidSTB_MEDIUM','','','0','0','','','text','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','16','0','0');
INSERT INTO `v9_model_field` VALUES('474','23','1','imgpath','台标','详情界面使用','','0','0','','','image','array (\n  \'size\' => \'100\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'0\',\n  \'upload_maxsize\' => \'\',\n  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','1','0','1','0','1','0','0','0');
INSERT INTO `v9_model_field` VALUES('475','26','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('476','26','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','21','1','0');
INSERT INTO `v9_model_field` VALUES('477','26','1','title','版本号','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','4','0','0');
INSERT INTO `v9_model_field` VALUES('478','26','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','22','1','0');
INSERT INTO `v9_model_field` VALUES('502','26','1','date_tested','测试日期','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'date\',\n  \'format\' => \'Y-m-d Ah:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','1','6','0','0');
INSERT INTO `v9_model_field` VALUES('480','26','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','11','0','0');
INSERT INTO `v9_model_field` VALUES('503','26','1','update_location','更新地址','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','1','7','0','0');
INSERT INTO `v9_model_field` VALUES('507','27','1','title','服务器','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('508','27','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');
INSERT INTO `v9_model_field` VALUES('482','26','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','23','1','0');
INSERT INTO `v9_model_field` VALUES('505','27','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('504','26','1','features','主要新特性','','','0','0','','','textarea','array (\n  \'width\' => \'100%\',\n  \'height\' => \'46\',\n  \'defaultvalue\' => \'\',\n  \'enablehtml\' => \'0\',\n)','','','','0','0','0','1','0','1','1','1','8','0','0');
INSERT INTO `v9_model_field` VALUES('500','26','1','release_date','发布日期','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'date\',\n  \'format\' => \'Y-m-d Ah:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','1','3','0','0');
INSERT INTO `v9_model_field` VALUES('501','26','1','force_update','强制升级','','','0','0','','','box','array (\n  \'options\' => \'是|1\r\n否|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'1\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','0','1','0','1','5','0','0');
INSERT INTO `v9_model_field` VALUES('485','26','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','10','0','0');
INSERT INTO `v9_model_field` VALUES('486','26','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','20','1','0');
INSERT INTO `v9_model_field` VALUES('506','27','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','3','1','0');
INSERT INTO `v9_model_field` VALUES('488','26','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('489','26','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('490','26','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('497','26','1','os_type','操作系统','','','0','0','','','box','array (\n  \'options\' => \'Android|1\r\niOS|2\',\n  \'boxtype\' => \'select\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','0','1','0','1','2','0','0');
INSERT INTO `v9_model_field` VALUES('492','26','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('496','26','1','term_id','终端类型','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_term_type\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'title\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','0','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('494','26','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('510','27','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','5','0','0');
INSERT INTO `v9_model_field` VALUES('512','27','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('515','27','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','4','0','0');
INSERT INTO `v9_model_field` VALUES('516','27','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('518','27','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('519','27','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('520','27','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('522','27','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('526','27','1','ip','地址','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','0','2','0','0');
INSERT INTO `v9_model_field` VALUES('524','27','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('527','28','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('528','28','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','11','1','0');
INSERT INTO `v9_model_field` VALUES('529','28','1','title','广告位名称','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('530','28','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','12','1','0');
INSERT INTO `v9_model_field` VALUES('589','30','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('532','28','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','13','0','0');
INSERT INTO `v9_model_field` VALUES('583','30','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('585','30','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('586','30','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('587','30','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('534','28','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('550','28','1','SPID','SPID','','','0','0','','','box','array (\n  \'options\' => \'ddssp|ddssp\r\nquanwangsp|quanwangsp\',\n  \'boxtype\' => \'select\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','0','1','0','1','5','0','0');
INSERT INTO `v9_model_field` VALUES('537','28','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('538','28','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('540','28','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('541','28','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('542','28','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('549','28','1','display_type','显示方式','','','0','0','','','box','array (\n  \'options\' => \'水平跑马灯|1\r\n垂直跑马灯|2\r\n图片翻转|3\r\n嵌入小视频|4\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'1\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','1','4','0','0');
INSERT INTO `v9_model_field` VALUES('544','28','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('548','28','1','ad_type','广告类型','','','0','0','','','box','array (\n  \'options\' => \'文本|1\r\n图片|2\r\n视频|3\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'1\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','1','3','0','0');
INSERT INTO `v9_model_field` VALUES('546','28','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('594','31','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('595','31','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','10','1','0');
INSERT INTO `v9_model_field` VALUES('596','31','1','title','游戏类型','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('597','31','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','11','1','0');
INSERT INTO `v9_model_field` VALUES('599','31','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('643','32','1','gm_title','游戏宣传标题','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','8','0','0');
INSERT INTO `v9_model_field` VALUES('644','32','1','gm_description','游戏描述','','','0','0','','','textarea','array (\n  \'width\' => \'100%\',\n  \'height\' => \'46\',\n  \'defaultvalue\' => \'\',\n  \'enablehtml\' => \'0\',\n)','','','','0','0','0','1','0','1','1','1','9','0','0');
INSERT INTO `v9_model_field` VALUES('645','32','1','gm_register_url','注册链接','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','10','0','0');
INSERT INTO `v9_model_field` VALUES('623','32','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','63','1','0');
INSERT INTO `v9_model_field` VALUES('601','31','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('647','32','1','gm_official_url','游戏官网','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','12','0','0');
INSERT INTO `v9_model_field` VALUES('621','32','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','60','0','0');
INSERT INTO `v9_model_field` VALUES('646','32','1','gm_login_url','登录链接','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','11','0','0');
INSERT INTO `v9_model_field` VALUES('604','31','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('605','31','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('637','32','1','game_type','游戏类型','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_game_type\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'title\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','1','1','1','1','2','0','0');
INSERT INTO `v9_model_field` VALUES('619','32','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','62','1','0');
INSERT INTO `v9_model_field` VALUES('607','31','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('608','31','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('609','31','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('616','32','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('617','32','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','60','1','0');
INSERT INTO `v9_model_field` VALUES('611','31','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('615','31','1','game_point','权重','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','1','2','0','0');
INSERT INTO `v9_model_field` VALUES('613','31','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('618','32','1','title','游戏名称','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','1','0','0');
INSERT INTO `v9_model_field` VALUES('638','32','1','game_theme','游戏题材','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','1','3','0','0');
INSERT INTO `v9_model_field` VALUES('639','32','1','gm_recom_level','推荐指数','','','0','0','','','box','array (\n  \'options\' => \'1|1\r\n2|2\r\n3|3\r\n4|4\r\n5|5\',\n  \'boxtype\' => \'select\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'\',\n  \'outputtype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','1','4','0','0');
INSERT INTO `v9_model_field` VALUES('640','32','1','gm_recom_popular','推荐人气','','','0','0','','','box','array (\n  \'options\' => \'1|1\r\n2|2\r\n3|3\r\n4|4\r\n5|5\',\n  \'boxtype\' => \'select\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','1','5','0','0');
INSERT INTO `v9_model_field` VALUES('626','32','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','61','0','0');
INSERT INTO `v9_model_field` VALUES('627','32','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','64','1','0');
INSERT INTO `v9_model_field` VALUES('642','32','1','gm_oper_company','运营厂商','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','7','0','0');
INSERT INTO `v9_model_field` VALUES('629','32','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('630','32','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('631','32','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('641','32','1','gm_deve_company','开发厂商','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','6','0','0');
INSERT INTO `v9_model_field` VALUES('633','32','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('635','32','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('648','32','1','gm_tag','游戏推荐标签','','','0','0','','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','1','1','1','1','13','0','0');
INSERT INTO `v9_model_field` VALUES('649','32','1','gm_logo','游戏logo',' 允许png/jpg 类型 (191 * 90)','','0','0','','','image','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'0\',\n  \'upload_maxsize\' => \'\',\n  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'0\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','1','0','1','0','1','14','0','0');
INSERT INTO `v9_model_field` VALUES('650','32','1','gm_name_icon','游戏名字前的小图标','允许png/jpg 类型 (16 * 16)','','0','0','','','image','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'0\',\n  \'upload_maxsize\' => \'\',\n  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'0\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','1','0','1','0','1','15','0','0');
INSERT INTO `v9_model_field` VALUES('651','32','1','gm_cover_image','游戏封面图片','允许png/jpg 类型 (210 * 118)','','0','0','','','image','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'0\',\n  \'upload_maxsize\' => \'\',\n  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'0\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','1','0','1','0','1','16','0','0');
INSERT INTO `v9_model_field` VALUES('652','32','1','gm_repre_image','游戏代表图片','允许png/jpg 类型 (374 * 435)','','0','0','','','image','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'0\',\n  \'upload_maxsize\' => \'\',\n  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'0\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','1','0','1','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('653','32','1','gm_is_recom','是否推荐','','','0','0','','','box','array (\n  \'options\' => \'推荐|1\r\n不推荐|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'0\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','1','18','0','0');
INSERT INTO `v9_model_field` VALUES('654','32','1','gm_is_popularize','是否推广','','','0','0','','','box','array (\n  \'options\' => \'推广|1\r\n不推广|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'0\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','1','19','0','0');
INSERT INTO `v9_model_field` VALUES('655','32','1','open_service','游戏开服','请用  日期|服务器名称  例如：2012-10-11|234服','','0','0','','','textarea','array (\n  \'width\' => \'100%\',\n  \'height\' => \'46\',\n  \'defaultvalue\' => \'\',\n  \'enablehtml\' => \'0\',\n)','','','','0','0','0','1','0','1','0','1','20','0','0');
INSERT INTO `v9_model_field` VALUES('657','28','1','term_id','终端类型','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_term_type\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'title\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','1','1','1','1','2','0','0');
INSERT INTO `v9_model_field` VALUES('661','13','1','PAD','支持PAD','','','0','0','','','box','array (\n  \'options\' => \'支持|1\r\n不支持|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'1\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('660','13','1','STB','支持STB','','','0','0','','','box','array (\n  \'options\' => \'支持|1\r\n不支持|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'1\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','0','52','0','0');
INSERT INTO `v9_model_field` VALUES('662','13','1','PHONE','支持PHONE','','','0','0','','','box','array (\n  \'options\' => \'支持|1\r\n不支持|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'1\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('663','13','1','PC','支持PC','','','0','0','','','box','array (\n  \'options\' => \'支持|1\r\n不支持|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'1\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'0\',\n)','','','','0','1','0','1','0','1','0','0','54','0','0');
INSERT INTO `v9_model_field` VALUES('664','13','1','channel','所属频道','只有电视栏目才需要选择','','0','0','','','linkfield','array (\n  \'link_type\' => \'2\',\n  \'table_name\' => \'v9_channel\',\n  \'select_title\' => \'channel_id,title\',\n  \'like_title\' => \'\',\n  \'where_field_1\' => \'\',\n  \'where_value_1\' => \'\',\n  \'where_field_2\' => \'\',\n  \'where_value_2\' => \'\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'channel_id\',\n  \'insert_type\' => \'id\',\n  \'size\' => \'\',\n)','','','','0','1','0','1','0','1','1','0','18','0','0');
INSERT INTO `v9_model_field` VALUES('665','28','1','type_id','类型ID','请确保在同一终端下不重复','','0','0','/^[0-9.-]+$/','','text','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','0','6','0','0');
INSERT INTO `v9_model_field` VALUES('666','33','1','catid','栏目','','','1','6','/^[0-9]{1,6}$/','请选择栏目','catid','array (\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','1','0','1','1','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('667','33','1','typeid','类别','','','0','0','','','typeid','array (\n  \'minnumber\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','1','1','0','0','3','1','0');
INSERT INTO `v9_model_field` VALUES('668','33','1','title','视频来源','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','2','0','0');
INSERT INTO `v9_model_field` VALUES('669','33','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','10','1','0');
INSERT INTO `v9_model_field` VALUES('671','33','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');
INSERT INTO `v9_model_field` VALUES('673','33','1','thumb','缩略图','','','0','100','','','image','array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','0','0','1','0','1','14','1','0');
INSERT INTO `v9_model_field` VALUES('689','33','1','icon_url','网站logo','','','0','0','','','image','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'0\',\n  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'0\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','1','0','1','0','0','4','0','0');
INSERT INTO `v9_model_field` VALUES('676','33','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');
INSERT INTO `v9_model_field` VALUES('677','33','1','posids','推荐位','','','0','0','','','posid','array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)','','','','0','1','0','1','0','0','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('679','33','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');
INSERT INTO `v9_model_field` VALUES('680','33','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');
INSERT INTO `v9_model_field` VALUES('681','33','1','template','内容页模板','','','0','30','','','template','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');
INSERT INTO `v9_model_field` VALUES('683','33','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');
INSERT INTO `v9_model_field` VALUES('690','24','1','source_id','视频来源','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_video_source\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'title\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n)','','','','0','1','0','1','0','1','1','1','0','0','0');
INSERT INTO `v9_model_field` VALUES('685','33','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');
INSERT INTO `v9_model_field` VALUES('696','13','1','asset_id','视频ID','','','0','0','','','asset','array (\n  \'defaultvalue\' => \'\',\n)','','','','0','1','1','1','0','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('697','24','1','asset_id','视频ID','','','0','0','','','asset','array (\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','0','1','0','0','2','0','0');
INSERT INTO `v9_model_field` VALUES('698','25','1','asset_id','视频ID','','','0','0','','','asset','array (\n  \'defaultvalue\' => \'\',\n)','','','','0','1','0','1','0','1','0','0','2','0','0');
INSERT INTO `v9_model_field` VALUES('699','25','1','path','海报图片','','','0','0','','','image','array (\n  \'size\' => \'60\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'0\',\n  \'upload_maxsize\' => \'\',\n  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','1','0','1','0','0','3','0','0');
INSERT INTO `v9_model_field` VALUES('700','13','1','channel_other','属于以上频道','<span style=\"color:red;\">如果电视节目不属于上面的频道请勾选</span>','','0','0','','','box','array (\n  \'options\' => \'属于|1\r\n不属于|0\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'1\',\n  \'outputtype\' => \'1\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','1','1','0','0','18','1','0');
INSERT INTO `v9_model_field` VALUES('701','16','1','icon_img_url','分类LOGO','','','0','0','','','image','array (\n  \'size\' => \'80\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'0\',\n  \'upload_maxsize\' => \'10240\',\n  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)','','','','0','1','0','1','0','1','0','0','0','0','0');
INSERT INTO `v9_model_field` VALUES('703','13','1','area_id','地区','','','0','0','','','linkfield','array (\n  \'link_type\' => \'2\',\n  \'table_name\' => \'v9_tags\',\n  \'select_title\' => \'id,title\',\n  \'like_title\' => \'\',\n  \'where_field_1\' => \'type\',\n  \'where_value_1\' => \'1\',\n  \'where_field_2\' => \'published\',\n  \'where_value_2\' => \'1\',\n  \'set_title\' => \'title\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n  \'size\' => \'\',\n)','','','','0','1','0','1','0','1','1','0','8','0','0');
INSERT INTO `v9_model_field` VALUES('704','13','1','parent_id','分集所在的总集的VID','<input type=\"button\" value=\"总集搜索\" id=\"parent_id_pop_menu\" class=\"button\" /> 仅用于电视剧、电视栏目，且此视频为分集时有意义；','','0','0','','','text','array (\n  \'size\' => \'\',\n  \'defaultvalue\' => \'\',\n  \'ispassword\' => \'0\',\n)','','','','0','1','0','1','0','1','1','0','22','0','0');
INSERT INTO `v9_model_field` VALUES('705','25','1','type','海报类型','','','0','0','','','linkfield','array (\n  \'link_type\' => \'1\',\n  \'table_name\' => \'v9_dbmover_poster_type\',\n  \'select_title\' => \'id,description,file_format,resolution_ratio\',\n  \'like_title\' => \'description\',\n  \'where_title\' => \'\',\n  \'set_title\' => \'description\',\n  \'set_id\' => \'id\',\n  \'insert_type\' => \'id\',\n  \'size\' => \'40\',\n)','','','','0','1','0','1','0','1','1','0','4','0','0');
INSERT INTO `v9_model_field` VALUES('706','13','1','aspect','画质','','','0','0','','','box','array (\n  \'options\' => \'低清|1\r\n标清|2\r\n高清|3\r\n超清|4\',\n  \'boxtype\' => \'radio\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n  \'width\' => \'80\',\n  \'size\' => \'1\',\n  \'defaultvalue\' => \'2\',\n  \'outputtype\' => \'0\',\n  \'filtertype\' => \'1\',\n)','','','','0','1','0','1','0','1','0','0','0','0','0');

